# Generated by Django 4.1.5 on 2023-02-01 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mothername', models.CharField(max_length=200)),
                ('fathername', models.CharField(max_length=200)),
                ('contact', models.IntegerField(max_length=20)),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=200)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
    ]
